# Generated by Django 4.2.3 on 2023-07-25 11:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('adminside', '0003_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='banner',
            old_name='banner_description',
            new_name='banner_discription',
        ),
    ]
