# Generated by Django 4.2.1 on 2023-07-27 10:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('adminside', '0004_rename_banner_description_banner_banner_discription'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='banner',
            name='Category',
        ),
    ]
