# Generated by Django 4.2.3 on 2023-08-29 10:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('adminside', '0007_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Banner',
        ),
    ]
