# Generated by Django 4.2.1 on 2023-08-17 07:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0014_alter_orderitem_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderitem',
            name='status',
            field=models.CharField(choices=[('Processing', 'Processing'), ('Shipped', 'Shipped'), ('pending', 'pending'), ('Delivered', 'Delivered'), ('Return', 'Return'), ('Cancelled', 'Cancelled')], default='pending', max_length=150),
        ),
    ]
