# Generated by Django 4.2.3 on 2023-08-17 07:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0015_alter_orderitem_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderitem',
            name='status',
            field=models.CharField(choices=[('pending', 'pending'), ('Shipped', 'Shipped'), ('Cancelled', 'Cancelled'), ('Return', 'Return'), ('Delivered', 'Delivered'), ('Processing', 'Processing')], default='pending', max_length=150),
        ),
    ]
