# Generated by Django 4.2.1 on 2023-08-20 06:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0018_alter_orderitem_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='Itemstatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_status', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Orderstatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_status', models.CharField(max_length=100)),
            ],
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='status',
            field=models.CharField(choices=[('Return', 'Return'), ('Delivered', 'Delivered'), ('Processing', 'Processing'), ('pending', 'pending'), ('Shipped', 'Shipped'), ('Cancelled', 'Cancelled')], default='pending', max_length=150),
        ),
    ]
