# Generated by Django 4.2.1 on 2023-08-21 06:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0021_orderitem_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderitem',
            name='status',
            field=models.CharField(choices=[('Shipped', 'Shipped'), ('Return', 'Return'), ('Processing', 'Processing'), ('Cancelled', 'Cancelled'), ('Delivered', 'Delivered'), ('pending', 'pending')], default='pending', max_length=150),
        ),
    ]
