# Generated by Django 4.2.3 on 2023-08-21 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0022_alter_orderitem_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderitem',
            name='status',
            field=models.CharField(choices=[('Delivered', 'Delivered'), ('Shipped', 'Shipped'), ('pending', 'pending'), ('Cancelled', 'Cancelled'), ('Processing', 'Processing'), ('Return', 'Return')], default='pending', max_length=150),
        ),
    ]
