# Generated by Django 4.2.3 on 2023-08-22 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0023_alter_orderitem_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderitem',
            name='status',
            field=models.CharField(choices=[('Cancelled', 'Cancelled'), ('Processing', 'Processing'), ('pending', 'pending'), ('Return', 'Return'), ('Delivered', 'Delivered'), ('Shipped', 'Shipped')], default='pending', max_length=150),
        ),
    ]
