# Generated by Django 4.2.1 on 2023-09-01 14:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0031_orderitem_coupon_orderitem_discount_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orderitem',
            old_name='coupon',
            new_name='coupon_amount',
        ),
        migrations.RenameField(
            model_name='orderitem',
            old_name='discount',
            new_name='offer_amount',
        ),
    ]
