# Generated by Django 4.2.1 on 2023-09-02 08:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('offer', '0001_initial'),
        ('checkout', '0032_rename_coupon_orderitem_coupon_amount_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderitem',
            name='offer_amount',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='offer.offer'),
        ),
    ]
