# Generated by Django 4.2.1 on 2023-09-02 08:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('coupon', '0001_initial'),
        ('checkout', '0033_alter_orderitem_offer_amount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderitem',
            name='coupon_amount',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='coupon.coupon'),
        ),
    ]
