# Generated by Django 4.2.1 on 2023-09-02 08:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0034_alter_orderitem_coupon_amount'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderitem',
            name='coupon_amount',
        ),
    ]
