# Generated by Django 4.2.3 on 2023-07-19 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='categories_discription',
        ),
        migrations.AddField(
            model_name='category',
            name='categories_description',
            field=models.TextField(default=1, max_length=300),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='category',
            name='categories',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='category',
            name='categories_image',
            field=models.ImageField(upload_to='categories_images/'),
        ),
    ]
