# Generated by Django 4.2.1 on 2023-07-27 10:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0007_remove_product_category'),
        ('adminside', '0005_remove_banner_category'),
        ('categories', '0002_remove_category_categories_discription_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Category',
        ),
    ]
