# Generated by Django 4.2.3 on 2023-08-15 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userprofile', '0002_wallet'),
    ]

    operations = [
        migrations.CreateModel(
            name='Userdp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profilephoto', models.ImageField(default='No Image Avilable', upload_to='photos/variant')),
            ],
        ),
    ]
