# Generated by Django 4.2.1 on 2023-08-16 14:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userprofile', '0003_userdp'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Userdp',
        ),
    ]
