# Generated by Django 4.2.1 on 2023-09-01 06:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userprofile', '0004_delete_userdp'),
    ]

    operations = [
        migrations.AddField(
            model_name='address',
            name='is_available',
            field=models.BooleanField(default=True, null=True),
        ),
    ]
