# Generated by Django 4.2.3 on 2023-08-29 10:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('categories', '0008_remove_category_categories_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='banner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('banner', models.CharField(max_length=200)),
                ('banner_image', models.ImageField(default='No image available', upload_to='photos/brand')),
                ('caption', models.TextField(max_length=200)),
                ('is_available', models.BooleanField(default=True)),
                ('category_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='categories.category')),
            ],
        ),
    ]
