# Generated by Django 4.2.1 on 2023-07-21 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_alter_product_category_alter_product_product_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='is_availble',
            field=models.BooleanField(default=False),
        ),
    ]
