# Generated by Django 4.2.3 on 2023-07-23 09:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_alter_product_is_availble'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='is_availble',
            new_name='is_available',
        ),
    ]
