# Generated by Django 4.2.1 on 2023-07-27 10:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_rename_is_availble_product_is_available'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='category',
        ),
    ]
