# Generated by Django 4.2.1 on 2023-07-27 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0008_product_category'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='product_image',
            new_name='product_image1',
        ),
        migrations.AddField(
            model_name='product',
            name='product_image2',
            field=models.ImageField(default='No image available', upload_to='photos/product'),
        ),
        migrations.AddField(
            model_name='product',
            name='product_image3',
            field=models.ImageField(default='No image available', upload_to='photos/product'),
        ),
    ]
