# Generated by Django 4.2.1 on 2023-08-08 04:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0009_rename_product_image_product_product_image1_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='product_description',
            field=models.TextField(blank=True),
        ),
    ]
