# Generated by Django 4.2.1 on 2023-08-12 06:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0013_color'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='product_image1',
        ),
        migrations.RemoveField(
            model_name='product',
            name='product_image2',
        ),
        migrations.RemoveField(
            model_name='product',
            name='product_image3',
        ),
    ]
